matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: lts/*
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  npm: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

install:
  - npm i yarn -g
  - yarn install
script:
  - yarn electron-dist

branches:
  only:
    - master
