matrix:
  include:
    - os: osx
      osx_image: xcode10.3
      language: node_js
      node_js: lts/*
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
        - SENTRY_RELEASE=$TRAVIS_TAG

branches:
  except:
    - hotfix/*
    - feature/*
    - release/*

# cache:
#   npm: true
#   directories:
#     - node_modules
#     - $HOME/.cache/electron
#     - $HOME/.cache/electron-builder

before_install:
  - npm i -g yarn
  - npm i -g @sentry/cli --unsafe-perm
install:
  - yarn install

script:
  - echo 1
# script:
#   - yarn lint
#   - yarn test --watchAll false
#   - yarn build
# after_success:
#   - yarn test --coverage --watchAll false
#   - cat ./coverage/lcov.info | yarn coveralls

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - bash scripts/electron-pack.sh
      - bash scripts/sentry-release.sh
    # on:
    #   tags: true
  - provider: releases
    before_deploy:
      - yarn electron-dist
    skip_cleanup: true
    api_key: $GITHUB_REPO_TOKEN
    file:
      - './dist/breader*'
      - './dist/latest*'
    draft: true
    on:
      tags: true
