matrix:
  include:
    - os: osx
      osx_image: xcode10.3
      language: node_js
      node_js: lts/*
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
        - SENTRY_RELEASE=$TRAVIS_TAG

branches:
  except:
    - hotfix/*
    - feature/*
    - release/*

cache: false

before_install:
  - npm i -g @sentry/cli --unsafe-perm
install:
  - yarn install

jobs:
  include:
    - stage: test
      script:
        - yarn lint
        - yarn test --watchAll false
        - yarn build
      after_success:
        - yarn test --coverage --watchAll false
        - cat ./coverage/lcov.info | yarn coveralls
    - stage: deploy
      if: tag IS present
      script:
        - yarn electron-dist
      after_success:
        - sentry-cli releases new $SENTRY_RELEASE
        - sentry-cli releases files $SENTRY_RELEASE upload-sourcemaps --rewrite ./build
        - sentry-cli releases finalize $SENTRY_RELEASE
      deploy:
        - provider: releases
          before_deploy:
            - yarn electron-dist
          skip_cleanup: true
          api_key: $GITHUB_REPO_TOKEN
          file:
            - './dist/breader*'
            - './dist/latest*'
          draft: true
          on:
            tags: true
