env:
  - SENTRY_RELEASE=$TRAVIS_TAG

matrix:
  include:
    - os: linux
      dist: bionic
      language: node_js
      node_js: lts/*
      services:
        - xvfb
    - os: osx
      osx_image: xcode10
      language: node_js
      node_js: lts/*
      if: tag IS present
    - os: windows
      language: node_js
      node_js: lts/*
      if: tag IS present

branches:
  except:
    - /^hotfix*$/
    - /^feature*$/
    - /^release*$/

cache: false

install:
  - if [ $TRAVIS_OS_NAME = osx ]; then yarn install; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then yarn install; fi
  - if [ $TRAVIS_OS_NAME = windows ]; then npm install; fi

script:
  - yarn lint
  - if [ $TRAVIS_OS_NAME = osx ]; then TZ=CST yarn test --watchAll false; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then TZ=CST xvfb-run -a yarn test --watchAll false; fi
  - yarn build
after_success:
  - if [ $TRAVIS_OS_NAME = linux ]; then TZ=CST xvfb-run -a yarn test:coverage --watchAll false; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then cat ./coverage/lcov.info | yarn coveralls; fi

before_deploy:
  - yarn electron-pack --publish never
  - yarn sentry-cli releases new $SENTRY_RELEASE
  - yarn sentry-cli releases files $SENTRY_RELEASE upload-sourcemaps --rewrite ./build
  - yarn sentry-cli releases finalize $SENTRY_RELEASE
  - ls ./
  - ls ./dist

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_REPO_TOKEN
  name: Release $TRAVIS_TAG
  draft: true
  file_glob: true
  file:
    - ./dist/*.zip
    - ./dist/*.dmg
    - ./dist/*.AppImage
    - ./dist/*.snap
    - ./dist/*.yml
    - ./dist/*.exe
  on:
    tags: true
