matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: stable
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  - yarn electron-dist

branches:
  only:
    - master
