# matrix:
#   include:
#     - os: osx
#       osx_image: xcode10.3
#       language: node_js
#       node_js: lts/*
#       env:
#         - ELECTRON_CACHE=$HOME/.cache/electron
#         - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
#         - SENTRY_RELEASE=$TRAVIS_TAG
language: node_js
node_js: stable

branches:
  except:
    - hotfix/*
    - feature/*
    - release/*

cache: false

install:
  - npm i -g @sentry/cli --unsafe-perm
script:
  - echo 1

deploy:
  - provider: script
    before_deploy:
      - sentry-cli --help
      - bash --help
    script:
      - bash --help
      - sentry-cli --help
