env:
  - SENTRY_RELEASE=$TRAVIS_TAG

matrix:
  include:
    - os: osx
      osx_image: xcode10.3
      language: node_js
      node_js: lts/*
      if: tag IS present
    - os: linux
      dist: bionic
      language: node_js
      node_js: lts/*
      services:
        - xvfb

branches:
  except:
    - hotfix/*
    - feature/*
    - release/*

cache: false

before_install:
  - npm i -g @sentry/cli --unsafe-perm
install:
  - yarn install

script:
  - yarn lint
  - if [ $TRAVIS_OS_NAME = osx ]; then yarn test; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then xvfb-run -a yarn test; fi
  - yarn build
after_success:
  - if [ $TRAVIS_OS_NAME = osx ]; then yarn test:coverage; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then xvfb-run -a yarn test:coverage; fi
  - cat ./coverage/lcov.info | yarn coveralls

before_deploy:
  - yarn electron-pack
  - sentry-cli releases new $SENTRY_RELEASE
  - sentry-cli releases files $SENTRY_RELEASE upload-sourcemaps --rewrite ./build
  - sentry-cli releases finalize $SENTRY_RELEASE
  - ls ./
  - ls ./dist

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_REPO_TOKEN
  name: Release $SENTRY_RELEASE
  draft: true
  file_glob: true
  file:
    - ./dist/*.zip
    - ./dist/*.dmg
    - ./dist/*.yml
    - ./dist/*.AppImage
    - ./dist/*.snap
  on:
    tags: true
