matrix:
  include:
    - os: osx
      osx_image: xcode10.3
      language: node_js
      node_js: lts/*
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
        - SENTRY_RELEASE=v1.6.2
        # - SENTRY_RELEASE=$TRAVIS_TAG

branches:
  except:
    - hotfix/*
    - feature/*
    - release/*

cache: false

before_install:
  - npm i -g @sentry/cli --unsafe-perm
install:
  - yarn install

script:
  - yarn lint
  - yarn test --watchAll false
  - yarn build
after_success:
  - yarn test --coverage --watchAll false
  - cat ./coverage/lcov.info | yarn coveralls

before_deploy:
  - yarn electron-pack
  - sentry-cli releases new $SENTRY_RELEASE
  - sentry-cli releases files $SENTRY_RELEASE upload-sourcemaps --rewrite ./build
  - sentry-cli releases finalize $SENTRY_RELEASE

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_REPO_TOKEN
  file:
    - './dist/breader*'
    - './dist/latest*'
  draft: true
  # on:
  #   tags: true
