matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: lts/*
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  npm: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

install:
  - npm i yarn -g
  - yarn install
  - yarn test --watchAll false
  - yarn build
script:
  - if [ "$TRAVIS_BRANCH" = "master" ] || [[ "$TRAVIS_BRANCH" =~ ^release ]]; then yarn electron-pack; fi
after_success:
  - yarn test --coverage --watchAll false
  - cat ./coverage/lcov.info | yarn coveralls
branches:
  - develop
  - master
  - release/*
