matrix:
  include:
    - os: osx
      osx_image: xcode10.3
      language: node_js
      node_js: lts/*
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

branches:
  - develop
  - master
  - release/*

cache:
  npm: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_install:
  - npm i -g yarn
  - npm i -g @sentry/cli --unsafe-perm
install:
  - yarn install

jobs:
  include:
    - stage: test
      script:
        - yarn lint
        - yarn test --watchAll false
        - yarn build
      after_success:
        - yarn test --coverage --watchAll false
        - cat ./coverage/lcov.info | yarn coveralls
    - stage: deploy
      if: tag IS present
      script:
        - yarn electron-dist
      after_success:
        - echo 1
