env:
  - SENTRY_RELEASE=v1.6.3
# - SENTRY_RELEASE=$TRAVIS_TAG

matrix:
  include:
    - os: osx
      osx_image: xcode10.3
      language: node_js
      node_js: lts/*
      if: tag IS present
    - os: linux
      dist: bionic
      language: node_js
      node_js: lts/*
      if: tag IS present
    - os: windows
      language: node_js
      node_js: lts/*

branches:
  except:
    - hotfix/*
    - feature/*
    - release/*

cache: false

before_install:
  - npm i -g @sentry/cli --unsafe-perm
  - rm yarn.lock
install:
  - yarn install

script:
  - yarn lint
  - yarn test --watchAll false
  - yarn build
after_success:
  - yarn test --coverage --watchAll false
  - cat ./coverage/lcov.info | yarn coveralls

before_deploy:
  - yarn electron-pack
  - sentry-cli releases new $SENTRY_RELEASE
  - sentry-cli releases files $SENTRY_RELEASE upload-sourcemaps --rewrite ./build
  - sentry-cli releases finalize $SENTRY_RELEASE
  - ls ./
  - ls ./dist

deploy:
  provider: releases
  skip_cleanup: true
  name: Release $SENTRY_RELEASE
  api_key: $GITHUB_REPO_TOKEN
  file_glob: true
  file:
    - ./dist/*.zip
    - ./dist/*.dmg
    - ./dist/*.yml
    - ./dist/*.exe
  draft: true
  # on:
  #   tags: true
